base_url = "https://chrismholland.com"
compile_sass = false
build_search_index = false
generate_robots_txt = true
generate_sitemap = true
generate_feeds = true
feed_filenames = ["atom.xml"]
title = "Chris Holland's Blog"
description = "On Technology, Inquiry, Musings."

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "base16-ocean-dark", filename = "syntax-theme-dark.css" },
  { theme = "solarized-light", filename = "syntax-theme-light.css" },
]
bottom_footnotes = true
render_emoji = true
definition_list = true
external_links_target_blank = true

[extra]
name="Chris Holland"
github_url = "https://github.com/cdaise"
email="chris@chrismholland.com"
