name = "zola-worker"
compatibility_date = "2025-08-15"
workers_dev = true

routes = [
  { pattern = "chrismholland.com", custom_domain = true },
  { pattern = "www.chrismholland.com", custom_domain = true }
]

[build]
command = 'zola build'

[assets]
directory = "./public/"
not_found_handling = "404-page"
